### PR TITLE
Add second buffer for partial bounding boxes detection

### PR DESCRIPTION
**Pull request by jonathan03020208**
Add a second layer buffer for partial bounding box detection, currently it only activate when bounding box is near the bottom of the screen (10 pixels range, 720>y>710, the conditions may be adjusted). 
It's not an overall improvement on every cameras and every date, so might need to consider which camera or date to use this functionality. 
The threshold of second buffer could be adjusted, maybe it will work better with our selected parameters.

Change the file extension for storing and reading files to fit the changes on variables data types.
Remove some redundant code.

### CODE REVIEW

**Comment by jonathan03020208** [comment]
@b06b01073  @Jonas0126 再麻煩你們確認看看有沒有問題了，謝謝!

**Comment by b06b01073** [comment]
有辦法調整一下讓左右畫面被裁切到的 bbox 也被考慮進去嗎

**Comment by jonathan03020208** [comment]
可以，是要左右邊的下半部就好，還是左右邊的全部?

**Comment by b06b01073** [comment]
> 可以，是要左右邊的下半部就好，還是左右邊的全部?

目前先設成全部

**Pull request merged**
